# Generated by Django 2.1.8 on 2020-02-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='项目名')),
                ('path', models.CharField(max_length=256, verbose_name='路径')),
                ('config', models.CharField(max_length=128, verbose_name='配置文件')),
                ('content', models.TextField(verbose_name='配置内容')),
                ('remark', models.CharField(max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '配置信息表',
            },
        ),
    ]
