# Generated by Django 2.1.8 on 2020-02-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200218_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='configfile',
            name='model_name',
            field=models.CharField(max_length=128, null=True, verbose_name='rsync模块名'),
        ),
        migrations.AddField(
            model_name='configfile',
            name='server_ip',
            field=models.GenericIPAddressField(null=True, protocol='IPV4', verbose_name='服务IP'),
        ),
    ]
