# Generated by Django 2.1.8 on 2020-03-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200218_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField(null=True, protocol='IPV4', verbose_name='服务IP')),
            ],
        ),
        migrations.RemoveField(
            model_name='configfile',
            name='server_ip',
        ),
        migrations.AddField(
            model_name='configfile',
            name='server_ip',
            field=models.ManyToManyField(to='app.ConfigIp'),
        ),
    ]
