# Generated by Django 2.1.8 on 2020-04-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200312_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configfile',
            name='path',
        ),
        migrations.AlterField(
            model_name='configfile',
            name='content',
            field=models.TextField(blank=True, verbose_name='配置内容'),
        ),
        migrations.RemoveField(
            model_name='configfile',
            name='server_ip',
        ),
        migrations.AddField(
            model_name='configfile',
            name='server_ip',
            field=models.GenericIPAddressField(null=True, protocol='IPV4', verbose_name='服务IP'),
        ),
        migrations.DeleteModel(
            name='ConfigIp',
        ),
    ]
