# Generated by Django 2.1.8 on 2020-04-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200409_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configfile',
            options={'verbose_name': '配置信息', 'verbose_name_plural': '配置信息'},
        ),
    ]
