# Generated by Django 2.1.8 on 2020-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200409_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='configfile',
            name='update_time',
            field=models.DateField(verbose_name='更新时间'),
        ),
    ]
