# Generated by Django 2.1.8 on 2020-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200409_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configfile',
            name='remark',
            field=models.CharField(blank=True, max_length=256, verbose_name='备注'),
        ),
    ]
